version: '3.8'

services:
  web:
    build: .
    container_name: jewelry_scraper
    ports:
      - "5000:5000"
      - "8000:8000"  # For monitoring metrics
    volumes:
      - ./jewelry_dataset:/app/jewelry_dataset
      - ./logs:/app/logs
      - ./config:/app/config
    environment:
      - FLASK_ENV=development
      - FLASK_APP=run.py
      - PYTHONUNBUFFERED=1
      - MAX_WORKERS=4
      - SCRAPING_DELAY=1.5
      - CHROME_BINARY=/usr/bin/chromium
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: '4G'
        reservations:
          cpus: '1'
          memory: '2G'
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - scraper_net

networks:
  scraper_net:
    driver: bridge