# docker-compose.yml

version: '3.8'

services:
  web:
    container_name: ebay_jewelry_scraper_web
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./jewelry_dataset:/app/jewelry_dataset
      - ./logs:/app/logs
    env_file:
      - .env
    restart: unless-stopped
