version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - API_KEY=80408040
    volumes:
      - ./jewelry_dataset:/app/jewelry_dataset
    restart: unless-stopped
