# Default configuration for jewelry scraping pipeline

# Scraping settings
scraper:
  output_dir: 'jewelry_dataset'
  max_items_per_category: 1000
  max_pages_per_category: 50
  max_retries: 3
  delay_between_requests: 1.5
  timeout: 30
  max_concurrent_requests: 4
  browser_settings:
    headless: true
    window_size: [1920, 1080]
    user_agent_rotation: true
    proxy_rotation: true

# Dataset settings
dataset:
  resnet:
    image_size: [224, 224]
    batch_size: 32
    train_split: 0.7
    val_split: 0.15
    test_split: 0.15
    augmentation_factor: 3
    normalize_mean: [0.485, 0.456, 0.406]
    normalize_std: [0.229, 0.224, 0.225]
  llava:
    image_size: [512, 512]
    max_caption_length: 256
    min_caption_length: 10
    train_split: 0.7
    val_split: 0.15
    test_split: 0.15

# Categories configuration
categories:
  necklace:
    - Choker
    - Pendant
    - Chain
  pendant:
    - Heart
    - Cross
    - Star
  bracelet:
    - Tennis
    - Charm
    - Bangle
  ring:
    - Engagement
    - Wedding
    - Fashion
  earring:
    - Stud
    - Hoop
    - Drop
  wristwatch:
    - Analog
    - Digital
    - Smart

# Storage settings
storage:
  raw_data_dir: 'raw_data'
  processed_data_dir: 'processed_data'
  dataset_dir: 'datasets'
  logs_dir: 'logs'
  max_raw_size_gb: 100
  cleanup_threshold_gb: 80

# Logging settings
logging:
  level: 'INFO'
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  file_rotation: '1 day'
  max_log_files: 30

# API settings
api:
  host: '0.0.0.0'
  port: 5000
  debug: true
  max_upload_size_mb: 10

# Monitoring settings
monitoring:
  enabled: true
  metrics_port: 8000
  collection_interval: 5
  history_size: 1000